language: node_js

sudo: false

node_js:
- 'iojs'
- '0.12'
- '0.10'

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++6' ]

before_install:
- source ./scripts/start_xvfb.sh

install:
- npm install --fallback-to-build=false

script:
- npm test
